### PR TITLE
Code stolen from my repository then turned into garbage

### PR DESCRIPTION
**Pull request by TheonlyIcebear**
All of this code is stolen from me, Jesus Christ. Then you removed the list comprehension because you can't understand how it works and replaced it with the most gibberish code. You also clearly don't understand how to use loops either so you make 10,000 variables called boo1, boo2, boo3, etc defining every single one. Please learn how to actually code in python at least if your gonna steal other's code and claim it as your own

### CODE REVIEW

**Comment by TheonlyIcebear** [comment]
image
Like what is this wait until this guy discovers what a loop is 🤦‍♂️

**Comment by TheonlyIcebear** [comment]
just uninstall python at that point, emberassing fr

**Comment by 2lay** [comment]
:skull:

**Comment by TheonlyIcebear** [comment]
> 💀

Best coder !!!

```py
games=scraper.get("https://rest-bf.blox.land/games/crash").json()
average10 = (games["history"][0]["crashPoint"] + games["history"][1]["crashPoint"] + games["history"][2]["crashPoint"] + games["history"][3]["crashPoint"] + games["history"][4]["crashPoint"] + games["history"][5]["crashPoint"] + games["history"][6]["crashPoint"] + games["history"][7]["crashPoint"] + games["history"][8]["crashPoint"] + games["history"][9]["crashPoint"]) / 10
average3 = (games["history"][0]["crashPoint"] + games["history"][1]["crashPoint"] + games["history"][2]["crashPoint"])
avg = average3 / 3
        ```

**Comment by 2lay** [comment]
yes man best coder, yesiamherenow code is so good it gave me 128gb of ram

**Pull request closed without merging**
